<?php

	require_once 'phpexel/PHPExcel.php';
	require 'helper.php';


	
	$data = get_all("discipline",$_GET['table']);

	$objPHPExcel = new PHPExcel();
	$styleArray = array(
    		'font'  => array(
        	'bold'  => true,
        	'color' => array('rgb' => '000000'),
        	'size'  => 14,
    	));


	$objPHPExcel->getProperties()->setCreator("Admin")
					->setLastModifiedBy("Admin")
					->setTitle($_GET['table'])
					->setSubject("Registered users")
					->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
					->setKeywords("office 2007 openxml php")
					->setCategory("Test result file");
	$objPHPExcel->getActiveSheet()->setTitle('Registered persons');
	$column = 0;
	$row = 3;

	$objPHPExcel->setActiveSheetIndex(0)
        	->setCellValue('A1', 'Man name')
        	->setCellValue('B1', 'Man surname')
        	->setCellValue('C1', 'Man id')
        	->setCellValue('D1', 'Lady name')
        	->setCellValue('E1', 'Lady surname')
        	->setCellValue('F1', 'Lady id')
		->setCellValue('G1', 'Country');
	$objPHPExcel->getActiveSheet()->getStyle('A1')->applyFromArray($styleArray);
	$objPHPExcel->getActiveSheet()->getStyle('B1')->applyFromArray($styleArray);
	$objPHPExcel->getActiveSheet()->getStyle('C1')->applyFromArray($styleArray);
	$objPHPExcel->getActiveSheet()->getStyle('D1')->applyFromArray($styleArray);
	$objPHPExcel->getActiveSheet()->getStyle('E1')->applyFromArray($styleArray);
	$objPHPExcel->getActiveSheet()->getStyle('F1')->applyFromArray($styleArray);
	$objPHPExcel->getActiveSheet()->getStyle('G1')->applyFromArray($styleArray);
	$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(25);
	$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(25);
	$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(25);
	$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(25);
	$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(25);
	$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(25);
	$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(25);
	$objPHPExcel->getActiveSheet()
	    ->getStyle('C1:C1000')
	    ->getAlignment()
	    ->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
	$objPHPExcel->getActiveSheet()
	    ->getStyle('F1:F1000')
	    ->getAlignment()
	    ->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);


	foreach($data as $record){
		foreach($record as $key=>$value){
			if(($key == 'man_name') || ($key == 'man_surname') || ($key == 'man_id') || ($key == 'woman_name') || ($key == 'woman_surname') || ($key == 'woman_id') || ($key == 'country')){
				$objPHPExcel->setActiveSheetIndex(0)->setCellValueByColumnAndRow($column, $row, $value);
				++$column;
			}
		}
		++$row;	
	}

	require_once 'phpexel/PHPExcel/IOFactory.php';
	$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
// If you want to output e.g. a PDF file, simply do:
//$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'PDF');
	$objWriter->save("".$_GET['table'].".xlsx");



	$file = $_GET['table'] .".xlsx";
	//echo $file;
	
	if (file_exists($file)) {
	
	    header('Content-Description: File Transfer');
	    header('Content-Type: application/octet-stream');
	    header("Content-Type: application/force-download");
	    header('Content-Disposition: attachment; filename=' . $file);
	    // header('Content-Transfer-Encoding: binary');
	    header('Expires: 0');
	    header('Cache-Control: must-revalidate, GET-check=0, pre-check=0');
	    header('Pragma: public');
	    header('Content-Length: ' . filesize($file));
	    ob_clean();
	    flush();
	    readfile($file);
	    exit;
	} else{
	}
?>
